### ISSUE TITLE
Infinite recursion on input "What is what?"

### ISSUE THREAD

**Issue by peterolson** [pandorabots/rosie#1]
The input

> What is what?

yields the response

> Too much recursion in AIML

**Comment by half5cat** [comment]
This can easily be fixed by adding a pattern for that specific case.

```
<category><pattern>WHAT IS WHAT</pattern>
<template>Well, that makes no sense.</template>
</category>
```

**Comment by pandorabots-admin** [comment]
fixed in z_update.aiml file.
