### ISSUE TITLE
How can i use the command <sraix>?

### ISSUE THREAD

**Issue by Paulingen** [pandorabots/rosie#2]
I am trying to use the command <sraix> to create my chat bot and i don't know how that i can use it.
Can someone help me?

**Comment by djfdev** [comment]
You can use `<sraix>` to send messages from one bot to another, and have the response appear as if the first bot had given it. So if your username is "paulingen" and you have two bots, "alice" and "alan", let's say that "alice" has the following category:

``` xml
<category>
  <pattern>WHO ARE YOU</pattern>
  <template><sraix bot="paulingen/alan"><input/></sraix></template>
</category>
```

When the input matches this category, "alice" will not provide the response directly. Instead, "alice" will return whichever response was provided by "alan".

**Comment by Paulingen** [comment]
Thanks.
